apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-config
  namespace: devops
data:
  API_KEY: "2f5ae96c-b558-4c7b-a590-a501ae1c3f6c"
  APP_NAME: "DevOps Microservice"
  APP_VERSION: "1.0.0"
---
apiVersion: v1
kind: Secret
metadata:
  name: devops-secrets
  namespace: devops
type: Opaque
stringData:
  jwt-secret: "your-secret-key-change-in-production"